### ISSUE TITLE
installing rembg failed when in conda python 3.11

### ISSUE THREAD

**Issue by ccartermices** [tobias17/sd-anim-utils#1]
Hey! I have created a python3.11 env in conda and installed rembg, however, bugs happened:
`ERROR: Ignored the following versions that require a different python version: 2.0.28 Requires-Python >3.7, <3.11; 2.0.29 Requires-Python >3.7, <3.11; 2.0.30 Requires-Python >3.7, <3.11; 2.0.31 Requires-Python >3.7, <3.11; 2.0.32 Requires-Python >3.7, <3.11
ERROR: Could not find a version that satisfies the requirement rembg (from versions: none)
ERROR: No matching distribution found for rembg`
How can i do for this? Thx!

**Comment by tobias17** [comment]
Hmmm, it looks like rembg is not updated to 3.11

I never actually figured out how to run rembg from within python, so I'm actually calling the package from the command line.

## To Fix this Issue
Use a lower python version (3.10 or below) to install rembg, and then continue using 3.11 normally
